Basic QA tools - php-cs-fixer and phpstan
matigda/gothinkster pull request #15
Opened 2017-11-01 02:46 UTC by kejwmen

To not overthink installation process (composer deps vs phars) I used `jakzal/phpqa:alpine` image and added `php-cs-fixer` and `phpstan` to lint target. These two are usually sufficient.

What do you think?

Related to #8

2017-11-01 09:38 UTC, matigda commented
Looks ok :) IMO just add mess detector check to it and we're good to go :)

2017-11-01 09:43 UTC, matigda commented on Makefile
> +	docker run -it --rm -v $(PWD):/app -w /app jakzal/phpqa:alpine php-cs-fixer fix --dry-run --diff src
I suggest @Symfony rules at least.

2017-11-01 09:59 UTC, matigda requested changes
Add mess detector and symfony rules in cs-fixer check and we're good to go.

2017-11-01 15:40 UTC, kejwmen commented
PHPMD `naming` and `controversial` rulesets are not included, some of them would be false positives and php-cs-fixer already covered what really matters.

After merging we need to make code pass linters checks.

2017-11-02 07:43 UTC, matigda commented
@kejwmen resolve conflicts :)

2017-11-04 22:59 UTC, kejwmen commented
rebased.

2017-11-05 00:16 UTC, matigda approved these changes

2017-11-05 00:19 UTC, merged